In [2]:
import numpy as np
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)

In [3]:
x1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [4]:
x2

array([ 0.,  1.,  2.])

In [5]:
x1*x2

array([[  0.,   1.,   4.],
       [  0.,   4.,  10.],
       [  0.,   7.,  16.]])

In [8]:
x1*x2[:, np.newaxis]

array([[  0.,   0.,   0.],
       [  3.,   4.,   5.],
       [ 12.,  14.,  16.]])