In [9]:
import numpy as np
x1 = np.arange(9.0).reshape((3, 3))+2
x2 = np.arange(3.0)+1


In [10]:
x1

array([[  2.,   3.,   4.],
       [  5.,   6.,   7.],
       [  8.,   9.,  10.]])

In [11]:
x2

array([ 1.,  2.,  3.])

In [14]:
x2[:,np.newaxis]/np.log(x1

array([[ 1.44269504,  0.91023923,  0.72134752],
       [ 1.24266987,  1.11622125,  1.02779668],
       [ 1.44269504,  1.36535884,  1.30288345]])